# Listen for DNS requests
port=53

# MAC 2
listen-address=10.7.22.85

no-resolv

# Upstream DNS servers
server=1.1.1.1
server=8.8.8.8

#project domain
address=/app.dotenv.test/10.7.30.220
address=/api.dotenv.test/10.7.30.220

no-hosts

# Cache DNS responses
cache-size=1000

#Logs
log-queries